# Generated by Django 4.0.4 on 2022-05-20 20:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Tutor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=250)),
                ('age', models.IntegerField(default=0)),
                ('cv', models.FileField(upload_to='files')),
                ('email', models.EmailField(max_length=254)),
                ('course', models.CharField(choices=[('python', 'python'), ('c++', 'c++'), ('javascript', 'javascript'), ('swift', 'swift'), ('html', 'html'), ('css', 'css'), ('Ruby', 'Ruby'), ('c#', 'c#'), ('c#', 'c#')], max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=250)),
                ('age', models.IntegerField(default=0)),
                ('email', models.EmailField(max_length=254)),
                ('course', models.CharField(choices=[('python', 'python'), ('c++', 'c++'), ('javascript', 'javascript'), ('swift', 'swift'), ('html', 'html'), ('css', 'css'), ('Ruby', 'Ruby'), ('c#', 'c#'), ('c#', 'c#')], max_length=200)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
